export const REMOVE_CONSTRUCTOR_INGREDIENTS = 'REMOVE_CONSTRUCTOR_INGREDIENTS';
export const SET_CONSTRUCTOR_INGREDIENTS = 'SET_CONSTRUCTOR_INGREDIENTS';
export const SET_CONSTRUCTOR_LOCK = 'SET_CONSTRUCTOR_LOCK';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';